### PR TITLE
remove unused react-vault dependency

### PR DESCRIPTION
**Pull request by MatteoGabriele**
I've removed the @apideck/react-vault package since it's never used. Probably added by mistake

### CODE REVIEW

**Review by jakeprins — APPROVED** [review]
Thank you!

**Comment by MatteoGabriele** [comment]
@jakeprins Any news? 👀 
Thanks again for your time. I'd like to update the package and remove all the unnecessary noise caused by these dependencies, as it obscures real warnings I might need to take care of.

Here is the output of my dependency installation every time I run it.
Screenshot 2024-05-21 at 13 31 24

**Comment by Gdewilde** [comment]
Hi, @MatteoGabriele; I will bring this up with the team.

**Comment by Gdewilde** [comment]
Hi @MatteoGabriele, I don't have an update yet. Let me discuss it during the planning next week.

**Comment by MatteoGabriele** [comment]
@Gdewilde Can you tell me what's in the 1.6.0 release since it's not listed on Github? This peer dependency was introduced with 1.5.2, so I can go back to 1.5.1 for now, but I'm not sure if I'll miss anything released with 1.6.0.

**Comment by nicklloyd** [comment]
@MatteoGabriele - looks like the workflow that should align the version in the package.json and tag a new release were not happening. 

As this package does little more than to serve as a iframe message transport for Vault, you should not be missing anything from 1.5.1 or 1.5.2.

**Comment by MatteoGabriele** [comment]
I received a Dependabot update for a library with the merged PR content. However, I noticed a discrepancy between the code on GitHub and the version published on npm. The last published version on npm is 1.6.0 from 7 months ago, and it still contains unused React packages. Could you please release version 1.6.1 with the recent fixes? This package is out of sync between Github and NPM. 
Thanks for your time again

**Pull request merged**
